package com.klyx.api.plugin

internal const val AUTO_NAME = "<auto>"

/**
 * Declares plugin metadata directly on the [KlyxPlugin] implementation.
 *
 * The Klyx Kotlin compiler plugin reads this annotation at compile time and:
 *
 * 1. **Validates it as a compile error** (not a runtime/on-device failure):
 *    - [id] must be reverse-DNS-shaped (e.g. `com.example.git-tools`)
 *    - [version] and [minAppVersion] must be valid semver
 *    - the annotated class must implement [KlyxPlugin]
 *    - the annotated class must have a public, no-argument constructor
 *      (required for [PathClassLoader][dalvik.system.PathClassLoader] instantiation
 *      on-device)
 *
 * 2. **Generates a real [PluginDescriptor]** as a companion property on the class,
 *    with [PluginDescriptor.entryClass] derived from the class's own fully qualified
 *    name, so it can never drift out of sync with a hand-typed string.
 *
 * 3. **Emits `plugin.json`** into the build directory at compile time, consumed by
 *    the `com.klyx.plugin` Gradle plugin when assembling the `.klyx` bundle. You no
 *    longer hand-author or maintain this file.
 *
 * ### Example
 * ```kotlin
 * @PluginManifest(
 *     id = "com.example.git-tools",
 *     version = "1.0.0",
 *     minAppVersion = "0.5.0"
 * )
 * class GitToolsPlugin : KlyxPlugin {
 *     override suspend fun onLoad() { /* ... */ }
 *     override suspend fun onStart() { /* ... */ }
 *     override suspend fun onStop() { /* ... */ }
 *     override suspend fun onUnload() { /* ... */ }
 * }
 *
 * // Generated by the compiler plugin, callable as GitToolsPlugin.descriptor:
 * // companion object {
 * //     val descriptor: PluginDescriptor = PluginDescriptor(
 * //         id = "com.example.git-tools",
 * //         version = "1.0.0",
 * //         minAppVersion = "0.5.0",
 * //         entryClass = "com.example.gittools.GitToolsPlugin"
 * //     )
 * // }
 * ```
 *
 * @property id Unique reverse-DNS identifier for the plugin.
 * @property name Display name. Defaults to [id] if left blank.
 * @property version Semver version of the plugin.
 * @property minAppVersion Minimum Klyx app version required, in semver form.
 * @property maxAppVersion Maximum Klyx app version supported, if any.
 * @property description A short description of the plugin's functionality.
 * @property icon Path (relative to the plugin module) to the plugin's icon.
 * @property license SPDX license identifier or short license name.
 *
 * @see PluginDescriptor
 * @see KlyxPlugin
 */
@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.BINARY)
@MustBeDocumented
annotation class PluginManifest(
    val id: String,
    val version: String = "0.1.0",
    val name: String = AUTO_NAME,
    val minAppVersion: String = "4.2.0",
    val maxAppVersion: String = "",
    val description: String = "",
    val icon: String = "",
    val license: String = "",
    val author: Author = Author(name = ""),
    val links: Links = Links(),
    val permissions: Array<String> = []
)

@Target(AnnotationTarget.ANNOTATION_CLASS)
@Retention(AnnotationRetention.BINARY)
annotation class Author(
    val name: String,
    val email: String = "",
    val url: String = "",
    val github: String = ""
)

@Target(AnnotationTarget.ANNOTATION_CLASS)
@Retention(AnnotationRetention.BINARY)
annotation class Links(
    val source: String = "",
    val issues: String = "",
    val website: String = "",
    val donate: String = ""
)
