package com.klyx.core.lsp

/**
 * https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocumentItem
 */
val languageIdentifiers = mapOf(
    "ABAP" to "abap",
    "Windows Bat" to "bat",
    "BibTeX" to "bibtex",
    "Clojure" to "clojure",
    "Coffeescript" to "coffeescript",
    "C" to "c",
    "C++" to "cpp",
    "C#" to "csharp",
    "CSS" to "css",
    "Diff" to "diff",
    "Dart" to "dart",
    "Dockerfile" to "dockerfile",
    "Elixir" to "elixir",
    "Erlang" to "erlang",
    "F#" to "fsharp",
    "Git" to "git-commit", // git also has git-rebase
    "Go" to "go",
    "Groovy" to "groovy",
    "Handlebars" to "handlebars",
    "HTML" to "html",
    "Ini" to "ini",
    "Java" to "java",
    "JavaScript" to "javascript",
    "JavaScript React" to "javascriptreact",
    "JSON" to "json",
    "LaTeX" to "latex",
    "Less" to "less",
    "Lua" to "lua",
    "Makefile" to "makefile",
    "Markdown" to "markdown",
    "Objective-C" to "objective-c",
    "Objective-C++" to "objective-cpp",
    "Perl" to "perl",
    "Perl 6" to "perl6",
    "PHP" to "php",
    "Powershell" to "powershell",
    "Pug" to "jade",
    "Python" to "python",
    "R" to "r",
    "Razor (cshtml)" to "razor",
    "Ruby" to "ruby",
    "Rust" to "rust",
    "SCSS" to "scss",
    "Sass" to "sass",
    "Scala" to "scala",
    "ShaderLab" to "shaderlab",
    "Shell Script (Bash)" to "shellscript",
    "SQL" to "sql",
    "Swift" to "swift",
    "TypeScript" to "typescript",
    "TypeScript React" to "typescriptreact",
    "TeX" to "tex",
    "Visual Basic" to "vb",
    "XML" to "xml",
    "XSL" to "xsl",
    "YAML" to "yaml"
)
