package com.klyx.core.icon

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val KlyxIcons.BrandFamily: ImageVector
    get() {
        if (_BrandFamily != null) return _BrandFamily!!

        _BrandFamily = ImageVector.Builder(
            name = "BrandFamily",
            defaultWidth = 24.dp,
            defaultHeight = 24.dp,
            viewportWidth = 960f,
            viewportHeight = 960f
        ).apply {
            path(
                fill = SolidColor(Color(0xFF000000))
            ) {
                moveTo(186f, 880f)
                quadToRelative(-54f, 0f, -80f, -22f)
                reflectiveQuadToRelative(-26f, -66f)
                quadToRelative(0f, -58f, 49f, -74f)
                reflectiveQuadToRelative(116f, -16f)
                horizontalLineToRelative(21f)
                verticalLineToRelative(-56f)
                quadToRelative(0f, -34f, -1f, -55.5f)
                reflectiveQuadToRelative(-6f, -35.5f)
                reflectiveQuadToRelative(-11.5f, -19.5f)
                reflectiveQuadTo(230f, 530f)
                quadToRelative(-9f, 0f, -16.5f, 3f)
                reflectiveQuadToRelative(-12.5f, 8f)
                quadToRelative(-4f, 5f, -5f, 10.5f)
                reflectiveQuadToRelative(1f, 11.5f)
                quadToRelative(6f, 11f, 14f, 21.5f)
                reflectiveQuadToRelative(8f, 24.5f)
                quadToRelative(0f, 25f, -17.5f, 42.5f)
                reflectiveQuadTo(159f, 669f)
                reflectiveQuadToRelative(-42.5f, -17.5f)
                reflectiveQuadTo(99f, 609f)
                quadToRelative(0f, -27f, 12f, -44f)
                reflectiveQuadToRelative(32.5f, -27f)
                reflectiveQuadToRelative(47.5f, -14f)
                reflectiveQuadToRelative(58f, -4f)
                quadToRelative(85f, 0f, 118f, 30.5f)
                reflectiveQuadTo(400f, 658f)
                verticalLineToRelative(147f)
                quadToRelative(0f, 19f, 4.5f, 28f)
                reflectiveQuadToRelative(15.5f, 9f)
                quadToRelative(12f, 0f, 19.5f, -18f)
                reflectiveQuadToRelative(9.5f, -56f)
                horizontalLineToRelative(11f)
                quadToRelative(-3f, 62f, -23.5f, 87f)
                reflectiveQuadTo(368f, 880f)
                quadToRelative(-43f, 0f, -67.5f, -13.5f)
                reflectiveQuadTo(269f, 826f)
                quadToRelative(-10f, 29f, -29.5f, 41.5f)
                reflectiveQuadTo(186f, 880f)
                moveToRelative(373f, 0f)
                quadToRelative(-20f, 0f, -32.5f, -16.5f)
                reflectiveQuadTo(522f, 828f)
                lineToRelative(102f, -269f)
                quadToRelative(7f, -17f, 22f, -28f)
                reflectiveQuadToRelative(34f, -11f)
                reflectiveQuadToRelative(34f, 11f)
                reflectiveQuadToRelative(22f, 28f)
                lineToRelative(102f, 269f)
                quadToRelative(8f, 19f, -4.5f, 35.5f)
                reflectiveQuadTo(801f, 880f)
                quadToRelative(-12f, 0f, -22f, -7f)
                reflectiveQuadToRelative(-15f, -19f)
                lineToRelative(-20f, -58f)
                horizontalLineTo(616f)
                lineToRelative(-20f, 58f)
                quadToRelative(-4f, 11f, -14f, 18.5f)
                reflectiveQuadTo(559f, 880f)
                moveToRelative(-324f, -29f)
                quadToRelative(13f, 0f, 22f, -20.5f)
                reflectiveQuadToRelative(9f, -49.5f)
                verticalLineToRelative(-67f)
                quadToRelative(-26f, 0f, -38f, 15.5f)
                reflectiveQuadTo(216f, 780f)
                verticalLineToRelative(11f)
                quadToRelative(0f, 36f, 4f, 48f)
                reflectiveQuadToRelative(15f, 12f)
                moveToRelative(407f, -125f)
                horizontalLineToRelative(77f)
                lineToRelative(-39f, -114f)
                close()
                moveToRelative(-37f, -285f)
                quadToRelative(-48f, 0f, -76.5f, -33.5f)
                reflectiveQuadTo(500f, 317f)
                quadToRelative(0f, -104f, 66f, -170.5f)
                reflectiveQuadTo(735f, 80f)
                quadToRelative(42f, 0f, 68f, 9.5f)
                reflectiveQuadToRelative(26f, 24.5f)
                quadToRelative(0f, 6f, -2f, 12f)
                reflectiveQuadToRelative(-7f, 11f)
                quadToRelative(-5f, 7f, -12.5f, 10f)
                reflectiveQuadToRelative(-15.5f, 1f)
                quadToRelative(-14f, -4f, -32f, -7f)
                reflectiveQuadToRelative(-33f, -3f)
                quadToRelative(-71f, 0f, -114f, 48f)
                reflectiveQuadToRelative(-43f, 127f)
                quadToRelative(0f, 22f, 8f, 46f)
                reflectiveQuadToRelative(36f, 24f)
                quadToRelative(11f, 0f, 21.5f, -5f)
                reflectiveQuadToRelative(18.5f, -14f)
                quadToRelative(17f, -18f, 31.5f, -60f)
                reflectiveQuadTo(712f, 202f)
                quadToRelative(2f, -13f, 10.5f, -18.5f)
                reflectiveQuadTo(746f, 178f)
                quadToRelative(18f, 0f, 27.5f, 9.5f)
                reflectiveQuadTo(779f, 211f)
                quadToRelative(-12f, 43f, -17.5f, 75f)
                reflectiveQuadToRelative(-5.5f, 58f)
                quadToRelative(0f, 20f, 5.5f, 29f)
                reflectiveQuadToRelative(16.5f, 9f)
                reflectiveQuadToRelative(21.5f, -8f)
                reflectiveQuadToRelative(29.5f, -30f)
                quadToRelative(2f, -3f, 15f, -7f)
                quadToRelative(8f, 0f, 12f, 6f)
                reflectiveQuadToRelative(4f, 17f)
                quadToRelative(0f, 28f, -32f, 54f)
                reflectiveQuadToRelative(-67f, 26f)
                quadToRelative(-26f, 0f, -44.5f, -14f)
                reflectiveQuadTo(691f, 386f)
                quadToRelative(-15f, 26f, -37f, 40.5f)
                reflectiveQuadTo(605f, 441f)
                moveToRelative(-485f, -1f)
                verticalLineToRelative(-220f)
                quadToRelative(0f, -58f, 41f, -99f)
                reflectiveQuadToRelative(99f, -41f)
                reflectiveQuadToRelative(99f, 41f)
                reflectiveQuadToRelative(41f, 99f)
                verticalLineToRelative(220f)
                horizontalLineToRelative(-80f)
                verticalLineToRelative(-80f)
                horizontalLineTo(200f)
                verticalLineToRelative(80f)
                close()
                moveToRelative(80f, -160f)
                horizontalLineToRelative(120f)
                verticalLineToRelative(-60f)
                quadToRelative(0f, -25f, -17.5f, -42.5f)
                reflectiveQuadTo(260f, 160f)
                reflectiveQuadToRelative(-42.5f, 17.5f)
                reflectiveQuadTo(200f, 220f)
                close()
            }
        }.build()

        return _BrandFamily!!
    }

private var _BrandFamily: ImageVector? = null

