package com.klyx.icons

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

val Icons.PictureAsPdf: ImageVector by lazy(LazyThreadSafetyMode.NONE) {
    ImageVector.Builder(
        name = "PictureAsPdf",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).apply {
        path(fill = SolidColor(Color.Black)) {
            moveTo(360f, 500f)
            horizontalLineToRelative(40f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(40f)
            quadToRelative(17f, 0f, 28.5f, -11.5f)
            reflectiveQuadTo(480f, 380f)
            verticalLineToRelative(-40f)
            quadToRelative(0f, -17f, -11.5f, -28.5f)
            reflectiveQuadTo(440f, 300f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(200f)
            close()
            moveTo(400f, 380f)
            verticalLineToRelative(-40f)
            horizontalLineToRelative(40f)
            verticalLineToRelative(40f)
            horizontalLineToRelative(-40f)
            close()
            moveTo(520f, 500f)
            horizontalLineToRelative(80f)
            quadToRelative(17f, 0f, 28.5f, -11.5f)
            reflectiveQuadTo(640f, 460f)
            verticalLineToRelative(-120f)
            quadToRelative(0f, -17f, -11.5f, -28.5f)
            reflectiveQuadTo(600f, 300f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(200f)
            close()
            moveTo(560f, 460f)
            verticalLineToRelative(-120f)
            horizontalLineToRelative(40f)
            verticalLineToRelative(120f)
            horizontalLineToRelative(-40f)
            close()
            moveTo(680f, 500f)
            horizontalLineToRelative(40f)
            verticalLineToRelative(-80f)
            horizontalLineToRelative(40f)
            verticalLineToRelative(-40f)
            horizontalLineToRelative(-40f)
            verticalLineToRelative(-40f)
            horizontalLineToRelative(40f)
            verticalLineToRelative(-40f)
            horizontalLineToRelative(-80f)
            verticalLineToRelative(200f)
            close()
            moveTo(320f, 720f)
            quadToRelative(-33f, 0f, -56.5f, -23.5f)
            reflectiveQuadTo(240f, 640f)
            verticalLineToRelative(-480f)
            quadToRelative(0f, -33f, 23.5f, -56.5f)
            reflectiveQuadTo(320f, 80f)
            horizontalLineToRelative(480f)
            quadToRelative(33f, 0f, 56.5f, 23.5f)
            reflectiveQuadTo(880f, 160f)
            verticalLineToRelative(480f)
            quadToRelative(0f, 33f, -23.5f, 56.5f)
            reflectiveQuadTo(800f, 720f)
            lineTo(320f, 720f)
            close()
            moveTo(320f, 640f)
            horizontalLineToRelative(480f)
            verticalLineToRelative(-480f)
            lineTo(320f, 160f)
            verticalLineToRelative(480f)
            close()
            moveTo(160f, 880f)
            quadToRelative(-33f, 0f, -56.5f, -23.5f)
            reflectiveQuadTo(80f, 800f)
            verticalLineToRelative(-560f)
            horizontalLineToRelative(80f)
            verticalLineToRelative(560f)
            horizontalLineToRelative(560f)
            verticalLineToRelative(80f)
            lineTo(160f, 880f)
            close()
            moveTo(320f, 160f)
            verticalLineToRelative(480f)
            verticalLineToRelative(-480f)
            close()
        }
    }.build()
}
