package com.klyx.core.cmd

import androidx.compose.ui.input.key.Key

fun Key.toKeyString(): String? {
    return when (this) {
        Key.A -> "A"
        Key.B -> "B"
        Key.C -> "C"
        Key.D -> "D"
        Key.E -> "E"
        Key.F -> "F"
        Key.G -> "G"
        Key.H -> "H"
        Key.I -> "I"
        Key.J -> "J"
        Key.K -> "K"
        Key.L -> "L"
        Key.M -> "M"
        Key.N -> "N"
        Key.O -> "O"
        Key.P -> "P"
        Key.Q -> "Q"
        Key.R -> "R"
        Key.S -> "S"
        Key.T -> "T"
        Key.U -> "U"
        Key.V -> "V"
        Key.W -> "W"
        Key.X -> "X"
        Key.Y -> "Y"
        Key.Z -> "Z"
        Key.Zero -> "0"
        Key.One -> "1"
        Key.Two -> "2"
        Key.Three -> "3"
        Key.Four -> "4"
        Key.Five -> "5"
        Key.Six -> "6"
        Key.Seven -> "7"
        Key.Eight -> "8"
        Key.Nine -> "9"
        Key.Enter -> "Enter"
        Key.Backspace -> "Backspace"
        Key.Spacebar -> "Space"
        Key.Tab -> "Tab"
        Key.Escape -> "Esc"
        Key.Comma -> ","
        Key.Period -> "."
        Key.Slash -> "/"
        Key.Backslash -> "\\"
        Key.Minus -> "-"
        Key.Plus -> "+"
        Key.Equals -> "="
        Key.LeftBracket -> "["
        Key.RightBracket -> "]"
        Key.CtrlLeft -> "Ctrl"
        Key.CtrlRight -> "Ctrl"
        Key.ShiftLeft -> "Shift"
        Key.ShiftRight -> "Shift"
        Key.AltLeft -> "Alt"
        Key.AltRight -> "Alt"
        Key.Delete -> "Delete"
        Key.Home -> "Home"
        Key.MoveEnd -> "End"
        Key.DirectionUp -> "Up"
        Key.DirectionDown -> "Down"
        Key.DirectionLeft -> "Left"
        Key.DirectionRight -> "Right"
        Key.F1 -> "F1"
        Key.F2 -> "F2"
        Key.F3 -> "F3"
        Key.F4 -> "F4"
        Key.F5 -> "F5"
        Key.F6 -> "F6"
        Key.F7 -> "F7"
        Key.F8 -> "F8"
        Key.F9 -> "F9"
        Key.F10 -> "F10"
        Key.F11 -> "F11"
        Key.F12 -> "F12"
        else -> null // Return null if no match is found
    }
}
